---
title: "R-package review"
description: |
   This blog post will be talked about the R Package Review - A review of R package 'COVID19dashboard'
author:
  - name: XITONG HE
    url: 
date: October 30, 2020
categories: 
  - R Package
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Overview

In this blog post I would be reviewing Yiwen Jiang's R package `COVID19dashboard`, making for one of assessment in ETC5523 course. This package contains coronavirus data, some functions about user interface-side and server-side, and launching shiny application. This package can be found via [GitHub](https://github.com/etc5523-2020/r-package-assessment-YIWEN-JIANG-github).
Moreover, more details about this package can be found [pkgdown site](https://etc5523-2020.github.io/r-package-assessment-YIWEN-JIANG-github/). 


The goal of COVID19dashboard package is to provide datasets and functions to run the COVID-19 shiny dashboard. The shiny application contained in the package, first launched on Oct 2020, aims to complement existing COVID-19 mapping dashboards (such as those developed by the [WHO](https://covid19.who.int/)) with several interactive features, including the timeline function and the ability to compare between countries.

### Data sets

To explore further details in this package, three data sets are included in it :

- `covid_raw`: The data comes from covid_raw.rda. The data contains the COVID-19 information of 210 countries since Dec 31, 2019.
- `visitors_total`: The data comes from visitors_total.rda. The data contains information on how the number of visitors changes sine pandemic for different places.
- `visitor_map`: The data comes from visitor_map.rda. The data added geometric information compare to visitors_total, it can be used to create a map plot.

### Main functions

The main functions in this package includes:

- **launch_app()**: This function allows the users to run the shiny dashboard via providing interactive visualisation and used to compare the difference between the countries.: 

- **add_comma()**: Label numbers in decimal format (e.g. 1,234). This function is used to insert a comma every three digits for columns in a data frame.

- **shiny_note()**: Add a note box into shiny app. It is a function that inserts a box that contains elements of note.  Using HTML tags to write you own notes for your shiny app, including How to interactive with the app, what does the output mean

- **date_range()**: Create date range input. This function provides date range input into the shiny app for the user selections. When clicked on, bring up calendars that the user can click on to select dates.
  
## What did I think this package would do? Did it do it?

When checking the Github page, the README file provides a basic information about this package, including the datasets, function explanation and clear picture of the shiny application. In the pkgdown site page, it provides more explanation for the shiny application about how to use the COVID-19 dashboard. By followed the instruction, I was downloaded the package and successfully able to explore the data sets or some functions in this package such as the `launch_app` could run the shiny application automatically and then explore it via different user inputs. Using the `add_comma` function could be labeled numbers in formatted style.

However, except for `launch_app` function is explained in the README and pkgdown file, the other three functions such as `shiny_note` function has not be included so the reviewer would have to download the package and go to help tab to explore those function.

## **Suggested Improvements**

**Code improvements**

I think the code in this package is well-written and easy to understand documentation. However, there are some improvements could be made to code. 
  
For example, the `date_range` function which is used to date range inputs into the shiny app. When clicked on, bring up calendars that the user can click on to select dates. But the given example in this function is hard to understand how to use this function, instead of running the original example with some complicated argument, the more specific example should be displayed for guiding the users more understandable how to select different date inputs . 

Here is an example: 
```
@examples
date_range (covid_raw,date_col = "date",1)
```

**Shiny App improvements**

The `covid19dashboard` shiny application is easy to explore the coronavirus data interactively via the different kinds of plots and tables such as clicking different line in the plotly graph which would display the table with the specific case type in different countries. However, there are some improvements can be made in the Shiny App.

First of all, in the data section, the `Select variable` option in the top left corner, which did not update the output of raw data table. Therefore, the updated input issue should be solve in this case.

In addition, the graph with the number of visitors change since the pandemic which would changed in plotly style, providing more interactive information for the users selection. For example, when selecting the Japan workplace, transit station and residential,users could visualize directly about the number of visitors change based on pandemic instead of only showing the time series trend, which could know more about the specific information such as how many visitors in the lowest point in these industry.

Furthermore,the presentation of the `summary table` should be followed the guideline such as left justify text, right justify numbers. 
    

**Documentation improvements**

In this package, there is enough documentation to provide the information of how to use the package and what would be contained in it. For the `launch_app` function, the documentation is easy to understand and could be reproduced the shiny app. However, the `shiny_note` function has more ambiguous argument in the function input and users would not know about how to use the function until see the example. The better way would be added the text parameter instead of using period(.). Further, the `Vignette`

 Elaborating on what is being plotting in the stringency function could be included as users will not know what the function does until running the application. Further, the `input` argument description is a bit vague, this argument can be left out as there is actually no argument needed to run the function. Providing an example for the interact function could be included to better help users understand how to use the function.    

## **Conclusion**

By reviewing the `covid19dashboard` package, I have learned how could I improve my shiny app and give more insightful to build up a package. From the Shiny App, it was interesting to see the number of visitors change because of pandemic compared with different countries across time in different industry. In addition, the trajectory graph with COVID-19 cases presents how the daily new cases change with the increase in the number of different case types, which gives more details in visualization about when the pandemic is getting better. Plotting the time series data in coronavirus, it can give more intuitive to visualize how the coronavirus changed across time in different countries.


## **Appendix**

### Package Review


#### Documentation

The package includes all the following forms of documentation:  

- [x] **Installation instructions for the package in README file:** Clear instruction and easy to follow how to install and use the package, giving a big picture overview of the package.

- [x] **Vignette(s)**: demonstrating major functionality that runs successfully locally. By using `pkgdown` site which give more details about the datasets and functions in this package.

- [x] **Function Documentation**: for all exported functions in R help. All functions are exported in this package have some form of documentation.

- [x] **Examples**: for all exported functions in R Help that run successfully locally.

#### Functionality

- [x] **Installation**: Installation succeeds as documented. The `covid19dashboard` package could be able to be installed into R without any errors.  
- [x] **Functionality**: Any functional claims of the software been confirmed.   
- [x] **Automated tests**: Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine without any errors.

Estimated hours spent reviewing:

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

#### Review Comments

The `covid19dashboard` package has passed all the unit tests of functionality in documentations and has proper vignette website page to introduce more information about this package. In addition, the Shiny App is included in this package by using the `launch_app` function to run it, which could be displayed successfully about how the COVID-19 pandemic have affected in different countries.







